// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanUp(arg1) {
  return window['go']['main']['App']['CleanUp'](arg1);
}

export function CompressPlaydateOS() {
  return window['go']['main']['App']['CompressPlaydateOS']();
}

export function DownloadLauncher(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadLauncher'](arg1, arg2, arg3, arg4);
}

export function DownloadPlaydateOS(arg1) {
  return window['go']['main']['App']['DownloadPlaydateOS'](arg1);
}

export function DownloadUPSM(arg1) {
  return window['go']['main']['App']['DownloadUPSM'](arg1);
}

export function ExtractLauncher(arg1) {
  return window['go']['main']['App']['ExtractLauncher'](arg1);
}

export function ExtractPlaydateOS(arg1) {
  return window['go']['main']['App']['ExtractPlaydateOS'](arg1);
}

export function ExtractUPSM(arg1) {
  return window['go']['main']['App']['ExtractUPSM'](arg1);
}

export function FinishRegistration(arg1) {
  return window['go']['main']['App']['FinishRegistration'](arg1);
}

export function GenerateUPSM(arg1, arg2) {
  return window['go']['main']['App']['GenerateUPSM'](arg1, arg2);
}

export function GetPin(arg1) {
  return window['go']['main']['App']['GetPin'](arg1);
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function InstallPatchedPlaydateOS(arg1) {
  return window['go']['main']['App']['InstallPatchedPlaydateOS'](arg1);
}

export function InstallUPSM(arg1, arg2) {
  return window['go']['main']['App']['InstallUPSM'](arg1, arg2);
}

export function UploadPatchedPlaydateOS(arg1) {
  return window['go']['main']['App']['UploadPatchedPlaydateOS'](arg1);
}
