// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanUp(arg1:string):Promise<void>;

export function CompressPlaydateOS():Promise<void>;

export function DownloadLauncher(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadPlaydateOS(arg1:string):Promise<void>;

export function DownloadUPSM(arg1:string):Promise<string>;

export function ExtractLauncher(arg1:string):Promise<void>;

export function ExtractPlaydateOS(arg1:boolean):Promise<void>;

export function ExtractUPSM(arg1:string):Promise<string>;

export function FinishRegistration(arg1:string):Promise<Record<string, any>>;

export function GenerateUPSM(arg1:string,arg2:string):Promise<string>;

export function GetPin(arg1:string):Promise<Record<string, any>>;

export function GetSerialPorts():Promise<Array<string>>;

export function InstallPatchedPlaydateOS(arg1:string):Promise<void>;

export function InstallUPSM(arg1:string,arg2:boolean):Promise<void>;

export function UploadPatchedPlaydateOS(arg1:string):Promise<void>;
